apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/stone-album-437618-f8/locations/us-central1-c/clusters/hrmis-cluster-1